#!/usr/bin/env bash
# Regenerate apps/frontend/src/licenses.generated.ts from:
#   * cargo-about (Rust workspace, with full license text per SPDX id)
#   * pnpm licenses (frontend deps, flat list grouped by SPDX expression)
#
# The output is committed and read by the About panel.
set -euo pipefail

# Pick up cargo/rustup if invoked from a non-login shell.
if [ -f "$HOME/.cargo/env" ]; then
  # shellcheck disable=SC1091
  source "$HOME/.cargo/env"
fi

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

rust_json="$(mktemp)"
trap 'rm -f "$rust_json"' EXIT

cargo about generate about.hbs -o "$rust_json" >/dev/null

frontend_json="$(cd apps/frontend && pnpm licenses list --json --prod)"

node --input-type=module -e "
import { readFileSync, writeFileSync } from 'node:fs';
const rust = JSON.parse(readFileSync('$rust_json', 'utf8')).licenses;
const fe = JSON.parse(process.argv[1]);

// cargo-about emits one entry per unique LICENSE file content; the same
// SPDX id appears many times (each crate ships its own copyright line).
// Collapses to one entry per SPDX id and merges usedBy.
const byId = new Map();
for (const L of rust) {
  if (!byId.has(L.id)) {
    byId.set(L.id, { id: L.id, name: L.name, text: L.text, usedBy: [] });
  }
  const acc = byId.get(L.id);
  // Keeps the longest text variant.
  if ((L.text || '').length > (acc.text || '').length) acc.text = L.text;
  for (const u of L.used_by || []) {
    acc.usedBy.push({
      name: u.name,
      version: u.version,
      repository: u.repository ?? null,
    });
  }
}
// Within each id, dedupe by name@version and sort alphabetically.
for (const acc of byId.values()) {
  const seen = new Set();
  acc.usedBy = acc.usedBy
    .filter(u => {
      const k = u.name + '@' + u.version;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}
const rustOut = [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));

const feOut = [];
for (const [spdx, pkgs] of Object.entries(fe)) {
  for (const p of pkgs) {
    for (const v of p.versions ?? [p.version]) {
      feOut.push({
        name: p.name,
        version: v,
        license: spdx,
        homepage: p.homepage ?? null,
        description: p.description ?? null,
      });
    }
  }
}
feOut.sort((a, b) => a.name.localeCompare(b.name));

// Full license texts go to a plain file bundled with the install
// (THIRD-PARTY-LICENSES.txt). MIT/Apache/BSD require the text to accompany
// the distributed software.
let txt = 'Daisy — third-party open-source notices\\n';
txt += 'Generated by scripts/gen-licenses.sh. Also at https://www.daisylocal.app/licenses\\n';
for (const L of rustOut) {
  txt += '\\n' + '='.repeat(72) + '\\n';
  txt += L.id + ' — used by: ' + L.usedBy.map(u => u.name + ' ' + u.version).join(', ') + '\\n';
  txt += '='.repeat(72) + '\\n\\n' + (L.text || '') + '\\n';
}
txt += '\\n' + '='.repeat(72) + '\\n';
txt += 'Intel Simplified Software License — used by: intel-mkl-src 0.8.1 (Windows builds only)\\n';
txt += '='.repeat(72) + '\\n\\n';
txt += 'Windows builds statically link Intel oneAPI Math Kernel Library (MKL),\\n';
txt += 'redistributed under the Intel Simplified Software License:\\n';
txt += 'https://www.intel.com/content/www/us/en/developer/articles/license/onemkl-license-faq.html\\n';
txt += 'Copyright (c) Intel Corporation. Linux and macOS builds use OpenBLAS instead.\\n';
txt += '\\n' + '='.repeat(72) + '\\nFrontend packages\\n' + '='.repeat(72) + '\\n';
for (const p of feOut) {
  txt += p.name + ' ' + p.version + ' — ' + p.license + (p.homepage ? ' — ' + p.homepage : '') + '\\n';
}
writeFileSync('THIRD-PARTY-LICENSES.txt', txt);

// The TS embed carries ids + who-uses only; no license text.
const rustLean = rustOut.map(({ id, name, usedBy }) => ({ id, name, usedBy }));
// Windows builds statically link Intel MKL (via speakrs' ndarray-linalg
// backend); cargo-about resolves the Linux graph and misses it.
rustLean.push({
  id: 'LicenseRef-Intel-Simplified',
  name: 'Intel Simplified Software License (Windows builds: Intel MKL)',
  usedBy: [{ name: 'intel-mkl-src', version: '0.8.1', repository: 'https://github.com/rust-math/intel-mkl-src' }],
});

const out = \`// AUTO-GENERATED by scripts/gen-licenses.sh. Do not edit by hand.
// Re-run after any dependency change.
// Full license texts: THIRD-PARTY-LICENSES.txt (bundled) / daisylocal.app/licenses.

export interface RustLicense {
  id: string;
  name: string;
  usedBy: { name: string; version: string; repository: string | null }[];
}

export interface FrontendPackage {
  name: string;
  version: string;
  license: string;
  homepage: string | null;
  description: string | null;
}

export const RUST_LICENSES: RustLicense[] = \${JSON.stringify(rustLean, null, 2)};

export const FRONTEND_PACKAGES: FrontendPackage[] = \${JSON.stringify(feOut, null, 2)};
\`;

writeFileSync('apps/frontend/src/licenses.generated.ts', out);
console.error(\`wrote apps/frontend/src/licenses.generated.ts (\${rustOut.length} rust license groups, \${feOut.length} frontend packages)\`);
" "$frontend_json"
